# -----------------------------------------------------
#  Copyright Iliass Mahjoub 2023.
#  Distributed under MIT License
#  (See accompanying file LICENSE)
# -----------------------------------------------------

name: CM4_LiteRTOS
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-ubuntu-stm32f446re:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        suite: [ all ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install gcc-arm-none-eabi
      - name: target-ubuntu-${{ matrix.suite }}
        working-directory: ./Build/VS
        run: |
          make -f ../Make/make_000.gmk ${{ matrix.suite }} TYP_OS=unix TYP_MCU=stm32f446re
          ls -la ../Bin/CM4_LiteRTOS_x64/cm4_litertos.elf ../Bin/CM4_LiteRTOS_x64/cm4_litertos.hex
